Get token for user if needed.

diff --git a/scripts/bkup b/scripts/bkup
--- a/scripts/bkup
+++ b/scripts/bkup
@@ -41,6 +41,22 @@ if [[ -z "${DOCKER_ID}" ]]; then
 fi
 readonly RPATH="bkup/${USER}/${DOCKER_ID}"
 
+function _check_remote() {
+  "${RCLONE}" ls remote: --max-depth 1 &> /dev/null
+}
+
+function _check_or_authorize_remote() {
+  if ! _check_remote; then
+    echo "Could not connect to remote.  Let's try to re-authorize:"
+    _cmd "${RCLONE}" config reconnect remote: --auto-confirm
+    if ! _check_remote; then
+      echo "Fatal: still can't connect to remote."
+      exit 1
+    fi
+  fi
+  echo "Remote connection OK."
+}
+
 function _cmd() {
   local ESCAPED_CMD
   ESCAPED_CMD="$(printf " %q" "$@")"
@@ -200,6 +216,8 @@ EOT
     echo "Made ${FILTERFILE}"
   fi
 
+  # Check for a valid token
+  _check_or_authorize_remote
 }
 
 ##########################################################################
@@ -217,6 +235,7 @@ The following configuration file specifies which files will not be backed up:
 EOT
 function bkup__backup() {
   _startup_checks
+  _check_or_authorize_remote
   local -a OPTS=(
     --links     # store symlinks as metadata
     --progress  # show progress
@@ -239,6 +258,7 @@ server, and reports which files are different.
 EOT
 function bkup__check() {
   _startup_checks
+  _check_or_authorize_remote
   local -a OPTS=(
     --links     # store symlinks as metadata
     --one-way
@@ -262,6 +282,7 @@ All specified paths are relative to the current working directory.
 EOT
 function bkup__ls() {
   _startup_checks
+  _check_or_authorize_remote
   local -a OPTS=(
     --links
     --max-depth 1
@@ -299,6 +320,7 @@ Usage: bkup cat <path>
 EOT
 function bkup__cat() {
   _startup_checks
+  _check_or_authorize_remote
   local -a OPTS=(
   )
 
@@ -335,6 +357,7 @@ All specified paths are relative to the current working directory.
 EOT
 function bkup__restore() {
   _startup_checks
+  _check_or_authorize_remote
   local -a OPTS=(
     --links
     --progress
@@ -385,6 +408,7 @@ modified by one or more of the following flags:
 EOT
 function bkup__restore_all() {
   _startup_checks
+  _check_or_authorize_remote
   local -a OPTS=(
     --links
     --max-delete 0
