gee find tweak

diff --git a/scripts/gee b/scripts/gee
--- a/scripts/gee
+++ b/scripts/gee
@@ -2634,8 +2634,13 @@ function gee__diff() {
 _register_help "find" "Finds a file by name in the current branch." <<'EOT'
 Usage: gee find [options] <expression>
 
-Searches the current branch for the specified expression.  Equivalent
-to running:
+Searches the current branch for a file whose name matches the specified
+expression.  Will initially search for the file without traversing symlinks.
+If it fails to find any files, it will search again in the bazel-bin
+subdirectory (and follow symlinks) to see if the file is generated by a bazel
+rule.
+
+Roughly equivalent to running:
 
     find -L "$(git rev-parse --show-toplevel)" -name .git -prune -or \
          -name "${expression}" -print
@@ -2655,7 +2660,15 @@ function gee__find() {
   CURRENT_BRANCH="$(_get_current_branch)"
   BRANCH_ROOT_DIR="$(_get_branch_rootdir "${CURRENT_BRANCH}")"
 
-  NOFAIL=1 _cmd find -L "${BRANCH_ROOT_DIR}" -name .git -prune -or -name "${1}" -print
+  (
+    # first look in the repo directory but without searching symlinks. find always returns 0, even
+    # if no files are found.  By piping through "grep .", grep will succeed if at least one line is
+    # processed, or will fail otherwise.
+    if ! _cmd find "${BRANCH_ROOT_DIR}" -name .git -prune -or -name "${1}" -print | grep .; then
+      # try search again, but look in bazel-bin with -L enabled.  Sort results by line length.
+      NOFAIL=1 _cmd find -L "${BRANCH_ROOT_DIR}/bazel-out" -name .git -prune -or -name "${1}" -print
+    fi
+  ) | perl -e 'print sort { length($a) <=> length($b) } <>'  # sort results by line length.
 }
 
 ##########################################################################
